### ISSUE TITLE
Bring in content from draft-ietf-lake-edhoc

### ISSUE THREAD

**Issue by marco-tiloca-sics** [core-wg/oscore-edhoc#1]
Move Section 7.2.1 and second half of Section 7.2.2 of https://tools.ietf.org/html/draft-ietf-lake-edhoc-06  to this document.

See https://github.com/lake-wg/edhoc/issues/75

**Comment by gselander** [comment]
Note PR with new definition of EDHOC-Exporter:
https://github.com/lake-wg/edhoc/pull/114

**Comment by marco-tiloca-sics** [comment]
Addressed by the merged https://github.com/core-wg/oscore-edhoc/pull/3
