### ISSUE TITLE
Server Processing and error

### ISSUE THREAD

**Issue by emanjon** [core-wg/oscore-edhoc#8]
Hi,

When the server processing the EDHOC + OSCORE Request, I think you have a lot of potential things that could happen. I think all of these five things could happen. The draft is not clear on if all of these are allowed or if some of them are forbidden.

1. CoAP without OSCORE, EDHOC Error as payload
2. CoAP without OSCORE, CoAP Error as payload
3. CoAP with OSCORE, EDHOC Error as payload
4. CoAP with OSCORE, CoAP Error as payload
5. CoAP with OSCORE, application payload

1. and 5. is to my understanding described in the draft.
2. and 4. are normal CoAP/OSCORE errors.
3. is possible if parsing of message_3 and derivation of OSCORE is possible but the Sever does not want to talk to the identified client. This would correspond to a protected error message in e.g., TLS.

**Comment by marco-tiloca-sics** [comment]
@emanjon , thanks for your input! Could you please double-check the numbering in the following text?

> 6. and 5. is to my understanding described in the draft.
> 
> 7. and 4. are normal CoAP/OSCORE errors.
> 
> 8. is possible if parsing of message_3 and derivation of OSCORE is possible but the Sever does not want to talk to the identified client. This would correspond to a protected error message in e.g., TLS.

It's hard to understand to which of the five items the sentences above refer to.

**Comment by marco-tiloca-sics** [comment]
Addressed in https://github.com/core-wg/oscore-edhoc/commit/eca3586d09285072006e3acbbd82891343b770d6
